name: Build & Deploy from github to aws 



on: 
  push:
    branches: [ main ]
jobs:
  Build:
    name: Build,tag, push docker iamge
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials (static keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}
      - name: Build,tag,push to ECR
        run: |
          set -e 
          IMAGE_NAME = zahn-care-frontend
          IMAGE_TAG="${{ github.run_number }}"
          ECR_IMAGE="579035389417.dkr.ecr.eu-north-1.amazonaws.com/zahn-care-frontend"
          
           aws ecr get-login-password --region "$AWS_REGION" \
            | docker login --username AWS --password-stdin "$ECR_IMAGE"

          #Build
          docker build -t $IMAGE_TAG:IMAGE_TAG .
          docker tag $IMAGE_TAG:$IMAGE_TAG $ECR_IMAGE

          docker push $ECR_IMAGE

